[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/src/*"
  [headers.values]
    Content-Type = "text/javascript"
